services:
  db:
    image: mariadb:lts
    ports:
      - 3307:3306
    env_file:
      - ./.env
    networks:
      - default
      
  server:
    build: ./
    volumes:
      - ./src:/app
    ports:
      - 8080:8080 
      - 443:443
    env_file:         
      - ./.env
    networks:
      - default

networks:
  default:
    driver: bridge