services:
  db:
    image: mariadb:lts
    ports:
      - 3307:3306
    env_file:
      - ./.env
    volumes:
      - ./src/scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - default
      
  server:
    build: 
      context: ./
      dockerfile: dockerfile
    volumes:
      - ./src:/app
    ports:
      - 8080:8080 
      - 8443:443
    env_file:         
      - ./.env
    networks:
      - default

networks:
  default:
    driver: bridge